---
service: contact-tracing-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  deploymentBucket:
    name: contact-tracing-api-serverless
    blockPublicAccess: true
    serverSideEncryption: AES256

package:
  include:
    - dist/**
  exclude:
    - '**'

functions:
  lambda-main:
    handler: dist/lambda-main.handler
    provisionedConcurrency: 1
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  # - serverless-domain-manager
  - serverless-deployment-bucket
  - serverless-layers
  - serverless-offline
  - serverless-prune-plugin

# TODO : Needs Route 53 domain first I guess?
custom:
#   customDomain:
#     domainName: contact-tracing-api.example.com
  prune:
    automatic: true
    includeLayers: true
    number: 5

# resources:
#   Resources:
