openapi: 3.0.0
info:
  title: contact-tracing-api
  version: '1.0'
  description: contact-tracing-api
  contact:
    url: 'https://github.com/codeforjapan/contact-tracing-api'
servers:
  - url: 'http://localhost:3100'
    description: Mock
  - url: 'http://localhost:3000'
    description: Local
  - url: 'https://35111ugog3.execute-api.ap-northeast-1.amazonaws.com/dev'
    description: DEV
paths:
  /users/me/close_contacts:
    post:
      summary: Add new close contacts
      tags:
        - app
      responses:
        '204':
          description: No Content
      operationId: post-v1-users-me-close_contacts
      security:
        - Bearer for APP: []
      description: |-
        - Store the list of close contacts of the positive user in Amazon DynamoDB.
          - These data will be used for the analysis of cluster occurrence.
        - The request is only made if the user agrees to provide information.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  tempID:
                    type: string
                    format: uuid
                  contactedAt:
                    type: string
                    format: date-time
                required:
                  - tempID
                  - contactedAt
    parameters: []
components:
  schemas: {}
  securitySchemes:
    Bearer for APP:
      type: http
      scheme: bearer
    Bearer for Admin:
      type: http
      scheme: bearer
tags:
  - name: app
  - name: admin
